# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: ../commons.yml
  shipment: ../shipment.yml

service:
  auth: true
  base-path: /v1/fulfillment
  endpoints:
    create:
      display-name: Create Fulfillment
      docs: Add the required inventory that needs to be shipped to the desired recipient from your specified location.
      path: ""
      method: POST
      request:
        name: CreateFulfillmentRequest
        body:
          properties:
            recipient: commons.Recipient
            location_id:
              docs: The ID of the location to which this manifest is being delivered
              type: string
            inventory:
              docs: The inventory that needs to be shipped in this fulfillment
              type: list<Inventory>
      response: FulfillmentResponse
      examples:
        - request:
            location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
            recipient: $commons.Recipient.Example1
            inventory:
              - id: "item_5og9NZ92SYzHKFTPYSEnVK"
                verified_qty: 25
              - id: "item_1nCNpqtyepe48BMNhzmW54"
                verified_qty: 50
                packaged_length: 2
                packaged_width: 3
                packaged_height: 4
                packaged_weight: 6
              - name: "Custom Item"
                verified_qty: 5
                packaged_length: 2
                packaged_width: 3
                packaged_height: 4
                packaged_weight: 6
                sku: "237489237489"
                image_url: "https://i.imgur.com/FKmX7dt.gif"
          response:
            body:
              status: 200
              data: $Fulfillment.Example1
              message: You created a fulfillment
              errors: []
              endpoint: /v1/fulfillment

    createParcel:
      docs: Add the box or boxes into which you're going to pack the inventory items.
      path: /{fulfillmentId}/parcels
      path-parameters:
        fulfillmentId: FulfillmentId
      method: POST
      request:
        name: CreateParcelRequest
        body:
          properties:
            parcel: Parcel
      response: FulfillmentResponse
      examples:
        - path-parameters:
            fulfillmentId: ful_dwdh3239ubcejbcjd
          request:
            parcel:
              id: prcl_dneidn333brb3jrj3b
              length: 10
              width: 10
              height: 10
          response:
            body:
              status: 200
              data: $Fulfillment.Example2
              message: You created a parcel
              errors: []
              endpoint: /v1/fulfillment/{fulfillment}/parcels

    packParcel:
      docs: Pack the items into the parcel(s) that you have added.
      path: /{fulfillmentId}/parcels/{parcelId}
      method: POST
      path-parameters:
        fulfillmentId: FulfillmentId
        parcelId: ParcelId
      request:
        name: PackParcelRequest
        body:
          properties:
            inventory: list<Inventory>
      response: FulfillmentResponse
      examples:
        - path-parameters:
            fulfillmentId: ful_dwdh3239ubcejbcjd
            parcelId: prcl_fnweifnief9292
          request:
            inventory:
              - id: "item_1nCNpqtyepe48BMNhzmW54"
                verified_qty: 2
              - id: "temp_5og9NZ92SYzHKFTPYSEnVK"
                verified_qty: 2
                damaged_qty: 5
          response:
            body:
              status: 200
              data: $Fulfillment.Example3
              message: You packed a parcel
              errors: []
              endpoint: /v1/fulfillment/{fulfillment}/parcels/{parcel}

    deleteParcel:
      docs: If you decide to delete the parcel from the fulfillment, any inventory attributed to that parcel will be removed and reset.
      path: /{fulfillmentId}/parcels/{parcelId}
      method: POST
      path-parameters:
        fulfillmentId: FulfillmentId
        parcelId: ParcelId
      response: commons.Response
      examples:
        - path-parameters:
            fulfillmentId: ful_dwdh3239ubcejbcjd
            parcelId: prcl_fnweifnief9292
          response:
            body:
              status: 200
              message: You deleted a parcel
              errors: []
              endpoint: /v1/fulfillment/{fulfillment}/parcels/{parcel}

    update:
      docs: Mark the fulfillment as packed.
      path: /{fulfillmentId}
      path-parameters:
        fulfillmentId: FulfillmentId
      method: POST
      request:
        name: UpdateFulfillmentRequest
        body:
          properties:
            status: FulfillmentStatus
      response: FulfillmentResponse
      examples:
        - path-parameters:
            fulfillmentId: ful_dwdh3239ubcejbcjd
          request:
            status: "packed"
          response:
            body:
              status: 200
              data: $Fulfillment.Example3
              message: You marked fulfillment as packed
              errors: []
              endpoint: /v1/fulfillment/{fulfillment}

types:
  FulfillmentId: string

  FulfillmentResponse:
    extends: commons.Response
    properties:
      data: Fulfillment

  Fulfillment:
    docs: The fulfillment model represents a unique fulfillment containing the inventory that was sent to the recipient.
    properties:
      cancel_reason:
        docs: If the fulfillment gets canceled, a reason can be optionally provided here.
        type: optional<string>
      created_at:
        docs: Time in epoch seconds when this resource was created
        type: integer
      complete_by:
        docs: Time in epoch seconds by which this fulfillment should be completed
        type: optional<integer>
      id:
        docs: The unique ID given to this fulfillment prefixed with ful_
        type: FulfillmentId
      inventory:
        docs: The inventory that needs to be shipped in this fulfillment
        type: list<Inventory>
      label_url:
        docs: The URL of the shipping label that gets generated when the fulfillment is completed
        type: optional<string>
      location_id:
        docs: The ID of the location to which this manifest is being delivered
        type: string
      metadata:
        docs: These are your metadata key value pairs added to the manifest
        type: optional<map<string, unknown>>
      order_number:
        docs: The order number that either you provided to the fulfillment or that PackageX added automatically
        type: optional<string>
      organization_id:
        docs: The ID of the organization that owns this fulfillment. In almost all cases, this will be your organization ID.
        type: optional<string>
      packaging_recommendations:
        docs: A list of the recommended way(s) to package to product into parcels if any shipping boxes are predefined in the settings. This is currently an empty array for all users.
        type: optional<list<string>>
      packing_slip_url:
        docs: The URL to the PDF of the packing slip for all items added to inventory
        type: optional<list<string>>
      parcels:
        docs: All parcels in the fulfillment and the inventory packed within them
        type: optional<list<Parcel>>
      rates_generated_at:
        docs: Time in epoch seconds when shipping rates were generated for this fulfillment. Shipping rates are only valid for 15 minutes after which new rates must be fetched.
        type: optional<integer>
      recipient:
        docs: Details about the contact receiving this shipment
        type: optional<commons.Recipient>
      sender:
        docs: Details about the contact sending this shipment
        type: optional<commons.Sender>
      shipment_id:
        docs: The ID of the shipment associated with this fulfillment, prefixed with ship_
        type: optional<string>
      shipment_rate_type: optional<ShipmentRateType>
      status: optional<FulfillmentStatus>
      updated_at:
        docs: Time in epoch seconds when this resource was last updated
        type: optional<integer>
    examples:
      - name: Example1
        value:
          id: ful_dwdh3239ubcejbcjd
          created_at: 1679591515
          location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
          recipient: $commons.Recipient.Example1
          inventory:
            - id: "item_5og9NZ92SYzHKFTPYSEnVK"
              verified_qty: 25
            - id: "item_1nCNpqtyepe48BMNhzmW54"
              verified_qty: 50
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
            - name: "Custom Item"
              verified_qty: 5
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
              id: "item_1wefewf33232hzmW54"
              sku: "237489237489"
              image_url: "https://i.imgur.com/FKmX7dt.gif"
      - name: Example2
        value:
          id: ful_dwdh3239ubcejbcjd
          created_at: 1679591515
          location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
          parcels:
            - id: prcl_fnweifnief9292
              length: 10
              width: 10
              height: 10
          recipient: $commons.Recipient.Example1
          inventory:
            - id: "item_5og9NZ92SYzHKFTPYSEnVK"
              verified_qty: 25
            - id: "item_1nCNpqtyepe48BMNhzmW54"
              verified_qty: 50
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
            - name: "Custom Item"
              verified_qty: 5
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
              id: "item_fewf44t43g4g43g4g4"
              sku: "237489237489"
              image_url: "https://i.imgur.com/FKmX7dt.gif"
      - name: Example3
        value:
          id: ful_dwdh3239ubcejbcjd
          status: packed
          created_at: 1679591515
          location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
          parcels:
            - id: prcl_fnweifnief9292
              length: 10
              width: 10
              height: 10
              inventory:
                id: "item_1nCNpqtyepe48BMNhzmW54"
                verified_qty: 2
          recipient: $commons.Recipient.Example1
          inventory:
            - id: "item_5og9NZ92SYzHKFTPYSEnVK"
              verified_qty: 25
            - id: "item_1nCNpqtyepe48BMNhzmW54"
              verified_qty: 50
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
            - name: "Custom Item"
              verified_qty: 5
              packaged_length: 2
              packaged_width: 3
              packaged_height: 4
              packaged_weight: 6
              sku: "237489237489"
              id: "item_1nCNpqtyepe48BMNhzmW54"
              image_url: "https://i.imgur.com/FKmX7dt.gif"

  FulfillmentStatus:
    docs: The status of the fulfillment
    enum:
      - created
      - processing
      - packed
      - completed
      - canceled

  ShipmentRateType:
    docs: The type of rate that was purchased for the shipment linked to the fulfillment without needing to query the shipment.
    enum:
      - in_person_pickup
      - curbside_pickup
      - locker_pickup
      - provider_delivery
      - offline_delivery
  
  Inventory:
    docs: An inventory model is an item or asset that is inside of a manifest, fulfillment, or parcel.
    properties:
      attributes: optional<InventoryAttributes>
      comment:
        docs: A free text field to add any comments about this item
        type: optional<string>
      created_at:
        docs: Time in epoch seconds when this resource was created
        type: optional<integer>
      verified_qty:
        docs: The amount of on hand inventory.
        type: optional<integer>
      damaged_qty:
        docs: The amount of on hand inventory that is deemed damaged
        type: optional<integer>
      manifested_qty:
        docs: The amount of inventory that is on a manifest that has not been added to inventory yet
        type: optional<integer>
      harmonized_code:
        docs: The harmonized system code for the item. This is required if you will be shipping this item internationally.
        type: optional<string>
      id:
        docs: The unique ID given to this product. This will stay the same even if the SKU or GTIN values are updated.
        type: optional<string>
      gtin:
        docs: The global identifier for the item, which is consistent across vendors for this item
        type: optional<string>
      sku:
        docs: The unique identifier that is added by you for this item
        type: optional<string>
      serial_number:
        docs: A unique number given to an asset
        type: optional<string>
      image_url:
        docs: A thumbnail image for the inventory
        type: optional<string>
      name:
        docs: The name of the item
        type: optional<string>
      origin_country:
        docs: The country that manufactured this item. This is required if shipping the item internationally
        type: optional<string>
      vendor:
        docs: The company that created the inventory
        type: optional<string>
      value:
        docs: The value of this each individual item in cents
        type: optional<integer>
      packaged_length:
        docs: The length of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_width:
        docs: The width of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_height:
        docs: The height of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_weight:
        docs: The weight of the item in pounds (lbs) when placed in shipping packaging
        type: optional<double>
  
  InventoryAttributes:
    docs: A list of enumerated strings to give more context to special items.
    enum:
      - alcohol
      - marijuana
      - pharma
      - dry_ice
      - lithium
  
  ParcelId: string

  Parcel:
    docs: A parcel or package that will be included in a shipment
    properties:
      attributes: optional<list<InventoryAttributes>>
      id:
        docs: The unique ID assigned to the parcel beginning with prcl_
        type: ParcelId
      length:
        docs: The length of the package in inches
        type: integer
      width:
        docs: The width of the package in inches
        type: integer
      height:
        docs: The height of the package in inches
        type: integer
      weight:
        docs: The weight of the package in pounds
        type: optional<integer>
      type: optional<shipment.PackageType>
      special_handling:
        docs: Any special handing instructions provided. Not all shipping providers support these
        type: optional<string>
      tracking_number:
        docs: The tracking number for this parcel if a shipment was purchased
        type: optional<string>
      label_url:
        docs: The shipping label PDF for this parcel if a shipment was purchased
        type: optional<string>
      inventory:
        docs: The inventory packed inside of the parcel
        type: optional<Inventory>
    examples:
      - name: Example1
        value:
          id: ebfweufe922828
          length: 2
          width: 5
          height: 4
          weight: 1
          type: usps_flat_rate_envelope