# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: ../commons.yml
  fulfillment: fulfillment.yml

service:
  auth: true
  base-path: /v1/items
  endpoints:
    create:
      path: ""
      method: POST
      display-name: Create Item
      request:
        name: CreateItemRequest
        body:
          properties:
            name:
              docs: The name of the item (only required property)
              type: string
            sku:
              docs: Either SKU or GTIN most likely on the barcode of items so it's best to include this so that barcode scanners play nicely.
              type: optional<string>
            gtin:
              docs: Either SKU or GTIN most likely on the barcode of items so it's best to include this so that barcode scanners play nicely.
              type: optional<string>
            packaged_length:
              docs: If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item
              type: optional<double>
            packaged_width:
              docs: If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item
              type: optional<double>
            packaged_height:
              docs: If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item
              type: optional<double>
            packaged_weight:
              docs: If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item
              type: optional<double>
      response: ItemResponse
      examples:
        - request:
            name: "My item name"
            sku: "123345"
            gtin: "987654"
            packaged_length: 5
            packaged_width: 6
            packaged_height: 7
            packaged_weight: 8
          response:
            body:
              status: 200
              data: $Item.Example1
              message: You created an item
              errors: []
              endpoint: /v1/items

    update:
      display-name: Update Item
      docs: Updates a single item. When updating inventory, you increment and decrement quantities by passing in positive and negative integers. Lastly, you can optionally provide a layout value to be more specific about the item's exact whereabouts in that location
      path: /{itemId}
      path-parameters:
        itemId: ItemId
      method: POST
      request:
        name: UpdateItemRequest
        body:
          properties:
            name:
              docs: Updated name
              type: optional<string>
            levels: optional<list<InventoryLevel>>
      response: ItemResponse
      examples:
        - path-parameters:
            itemId: given-item-id
          request:
            name: "Updated Name"
            levels:
              - location_id: "loc_8GiCVuqZqBJi43v2WebaME"
                verified_qty: 30
                id: lvl_fewfwef90c803cecee
              - location_id: "loc_dKa43ncARLdGENQPUq2CoX"
                verified_qty: -50
                id: lvl_fewfwef90c803cecee
          response:
            body:
              status: 200
              data: $Item.Example2
              message: You updated an item
              errors: []
              endpoint: /v1/item/{item}

    retrieve:
      display-name: Retrieve Item
      docs: Gets a single item
      path: /{itemId}
      path-parameters:
        itemId: string
      method: GET
      response: ItemResponse

    list:
      display-name: List Items
      docs: Gets all items
      path: ""
      method: GET
      response: ListItemResponse

    delete:
      docs: deletes a single item
      path: /{itemId}
      path-parameters:
        itemId: ItemId
      method: DELETE
      response: commons.Response
      examples:
        - path-parameters:
            itemId: debebw3933hden
          response:
            body:
              status: 200
              message: You deleted an item
              errors: []
              endpoint: /v1/item/{item}

types:
  ItemId: string

  ItemResponse:
    extends: commons.Response
    properties:
      data: Item
  
  ListItemResponse: 
    extends: commons.Response
    properties:
      data: list<Item>

  Item:
    properties:
      attributes: optional<fulfillment.InventoryAttributes>
      color:
        docs: Any value can be added here
        type: optional<string>
      created_at:
        docs: Time in epoch seconds when this resource was created
        type: integer
      description:
        docs: The details about the item
        type: optional<string>
      gtin:
        docs: The global identifier for the item, which is consistent across vendors for this item
        type: optional<string>
      harmonized_code:
        docs: The harmonized system code for the item. This is required if you will be shipping this item internationally.
        type: optional<string>
      id:
        docs: The unique ID given to this product. This will stay the same even if the SKU or GTIN values are updated.
        type: ItemId
      images:
        docs: A list of URLs of images that have been added for this item
        type: optional<list<string>>
      levels:
        docs: Information about inventory levels for this item across various locations and layouts
        type: optional<list<InventoryLevel>>
      metadata:
        docs: Any custom metadata that you have added
        type: optional<map<string, unknown>>
      name:
        docs: The name of the item
        type: string
      length:
        docs: The length of the item in inches
        type: optional<double>
      width:
        docs: The width of the item in inches
        type: optional<double>
      height:
        docs: The height of the item in inches
        type: optional<double>
      weight:
        docs: The weight of the item in pounds (lbs)
        type: optional<double>
      packaged_length:
        docs: The length of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_width:
        docs: The width of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_height:
        docs: The height of the item in inches when placed in shipping packaging
        type: optional<double>
      packaged_weight:
        docs: The weight of the item in pounds (lbs) when placed in shipping packaging
        type: optional<double>
      origin_country:
        docs: The country that manufactured this item. This is required if shipping the item internationally
        type: optional<string>
      organization_id:
        docs: The unique identifier for the organization that owns this item. This will always be your organization ID
        type: optional<string>
      status: optional<string>
      size:
        docs: The size of the item. This is used for display purposes on a product page. This is common when adding something like a "small" or "large" variation.
        type: optional<string>
      sku:
        docs: The SKU of the item added by you
        type: optional<string>
      total_verified:
        docs: The total verified inventory count across all levels
        type: optional<integer>
      total_damaged:
        docs: The total damaged inventory count across all levels
        type: optional<integer>
      total_manifested:
        docs: The total inventory count that is on a manifest
        type: optional<integer>
      total_reserved:
        docs: The total inventory count that is reserved
        type: optional<integer>
      updated_at:
        docs: Time in epoch seconds when this resource was updated
        type: optional<integer>
      value:
        docs: The value of this each individual item in cents
        type: optional<integer>
    examples:
      - name: Example1
        value:
          created_at: 1679591515
          id: debebw3933hden
          name: "My item name"
          sku: "123345"
          gtin: "987654"
          packaged_length: 5
          packaged_width: 6
          packaged_height: 7
          packaged_weight: 8
          status: created
      - name: Example2
        value:
          created_at: 1679591515
          id: debebw3933hden
          name: "Updated Name"
          sku: "123345"
          gtin: "987654"
          packaged_length: 5
          packaged_width: 6
          packaged_height: 7
          packaged_weight: 8
          status: created
          updated_at: 1679591515
          levels:
            - location_id: "loc_8GiCVuqZqBJi43v2WebaME"
              verified_qty: 60 # whatever value was previously plus 30
              id: lvl_dnqwn23ir23irb23rb23uibc
            - location_id: "loc_dKa43ncARLdGENQPUq2CoX"
              verified_qty: 10 # whatever value was previously minus 50
              id: lvl_fewfwef90c803cecee

  InventoryLevel:
    properties:
      id:
        docs: The ID for the level that starts with lvl_
        type: string
      location_id:
        docs: The ID of the location this in which this inventory level is housed
        type: string
      layout_id:
        docs: The layout ID within the location where this inventory can be found
        type: optional<string>
      layout_name:
        docs: The name of the layout this item is on.
        type: optional<string>
      verified_qty:
        docs: The amount of on hand inventory.
        type: optional<integer>
      damaged_qty:
        docs: The amount of on hand inventory that is deemed damaged
        type: optional<integer>
      manifested_qty:
        docs: The amount of inventory that is on a manifest that has not been added to inventory yet
        type: optional<integer>
      reserved_qty:
        docs: Inventory that has been reserved by being pulled out of the verified_qty count, usually due to being attributed to a fulfillment
        type: optional<integer>
