# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: ../commons.yml
  fulfillment: fulfillment.yml

service:
  auth: true
  base-path: /v1/manifest
  endpoints:
    create:
      docs: To create a manifest, you only need to include the location_id and specify the inventory items that you want to add.
      display-name: Create Manifest
      path: ""
      method: POST
      request:
        name: CreateManifestRequest
        body:
          properties:
            location_id:
              docs: The ID of the location to which this manifest is being delivered
              type: string
            inventory:
              docs: The inventory that is included in the manifest
              type: list<fulfillment.Inventory>
      response: ManifestResponse
      examples:
        - request:
            location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
            inventory:
              - id: "item_pu8iNbturZy5zvB4zaUZ8t"
                manifested_qty: 50
              - sku: "DRC123"
                manifested_qty: 50
              - gtin: "123456789"
                manifested_qty: 50
          response:
            body:
              status: 200
              data: $Manifest.Example1
              message: You created a manifest
              errors: []
              endpoint: /v1/manifest
              
    update: 
      docs: Before you can update a manifest, you'll need to update its status to accepted. When all items have been verified, you are able to update the status of the manifest to 'completed'.
      display-name: Update Manifest
      path: /{manifestId}
      method: POST
      path-parameters:
        manifestId: ManifestId
      request: 
        name: UpdateManifestStatusRequest
        body: 
          properties:
            status: ManifestStatus
      response: ManifestResponse
      examples: 
        - path-parameters:
            manifestId: msft_deuibcud2fwefwec33
          request:
            status: accepted
          response:
            body: 
              status: 200
              data: $Manifest.Example1
              message: You updated a manifest
              errors: []
              endpoint: /v1/manifest/msft_deuibcud2fwefwec33

    retrieve:
      docs: Gets a single manifest
      display-name: Retrieve Manifest
      path: /{manifestId}
      path-parameters:
        manifestId: ManifestId
      method: GET
      response: ManifestResponse

    list:
      docs: Gets all manifests
      display-name: List Manifest
      path: ""
      method: GET
      response: ListManifestResponse

types:
  ManifestResponse:
    extends: commons.Response
    properties:
      data: Manifest
  
  ListManifestResponse:
    extends: commons.Response
    properties:
      data: list<Manifest>

  ManifestId: string

  Manifest:
    docs: The manifest model represents a unique manifest containing the inventory that you would like to track.
    properties:
      created_at:
        docs: Time in epoch seconds when this resource was created
        type: integer
      created_inventory:
        docs: Inventory must be created before the manifest can be acted upon. It is common for this to be empty.
        type: optional<list<fulfillment.Inventory>>
      estimated_delivery:
        docs: Time in epoch seconds when we estimate the delivery will occur.
        type: optional<integer>
      id:
        docs: The unique ID given to this manifest prefixed with msft_
        type: ManifestId
      inventory:
        docs: The inventory that is included in the manifest
        type: list<fulfillment.Inventory>
      location_id:
        docs: The ID of the location to which this manifest is being delivered
        type: string
      metadata:
        docs: These are your metadata key value pairs added to the manifest
        type: optional<map<string, unknown>>
      order_number:
        docs: The order number that either you provided to the manifest or that PackageX added automatically
        type: optional<string>
      organization_id:
        docs: The ID of the organization that owns this manifest. In almost all cases, this will be your organization ID.
        type: optional<string>
      tracking_numbers:
        docs: A list of all tracking numbers for this manifest. When added, trackers will be created for each tracking number which will then update the estimated_delivery property.
        type: optional<list<string>>
      status: optional<ManifestStatus>
      updated_at:
        docs: Time in epoch seconds when this item was last updated
        type: optional<integer>
    examples:
      - name: Example1
        value:
          created_at: 1679591515
          id: msft_deuibcud2fwefwec33
          location_id: "loc_afnHMjVUn3gnrvxU5zMvkX"
          status: accepted
          inventory:
            - id: "item_pu8iNbturZy5zvB4zaUZ8t" # Create by ID
              manifested_qty: 50
            - sku: "DRC123" # Create by SKU. If SKU doesn't exist we'll create one
              manifested_qty: 50
            - gtin: "123456789" # Create by GTIN.
              manifested_qty: 50

  ManifestStatus:
    docs: The status of the manifest
    enum:
      - requested
      - accepted
      - processing
      - completed
      - void
